export const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS';
// fetch
export const CART_FETCH_ITEMS_START = 'CART_FETCH_ITEMS_START';
export const CART_FETCH_ITEMS_SUCCESS = 'CART_FETCH_ITEMS_SUCCESS';
export const CART_FETCH_ITEMS_FAIL = 'CART_FETCH_ITEMS_FAIL';
